/* dsh-subagent-panel client bundle — generated by scripts/build.mjs from src/client/ */
window.__ModuleLoader__.load({
  id: "dsh-subagent-panel",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;

//#region src/client/locales.js
/**
 * Dictionaries for the `subagent-panel` namespace. Keys stay flat and stable.
 * Both shipped locales are required at registration (bilingual balance).
 *
 * Only the entry points need copy now — the child session's own view is
 * rendered by the shell, which owns its own dictionaries.
 */

/** Locale namespace id. */
const NS = 'subagent-panel';

/** @typedef {(key: string) => string} Translate */

/** English dictionary. */
const en = {
  'card.running': 'Running',
  'card.inactive': 'Idle',
  'card.diagnostic': 'Unavailable',
  'card.open': 'Open this subagent session',
  'card.noLabel': 'untitled subagent',
  'card.children': 'has nested subagents',
  'trigger.label': 'Subagents',
  'trigger.empty': 'No subagents in this session yet',
};

/** Chinese dictionary. */
const zh = {
  'card.running': '运行中',
  'card.inactive': '空闲',
  'card.diagnostic': '不可用',
  'card.open': '打开这个子代理会话',
  'card.noLabel': '未命名子代理',
  'card.children': '含嵌套子代理',
  'trigger.label': '子代理',
  'trigger.empty': '当前会话还没有子代理',
};
//#endregion

//#region src/client/pure.js
/**
 * Pure logic for the subagent panel: catalog rows in, owned view models out.
 * Touches no React and no Cordis object, so the components never read live
 * runtime data directly and this file stays unit-testable in Node.
 */

/** @typedef {'running'|'idle'|'diagnostic'} CardStatus */

/**
 * Derive a card's status from one (structural) catalog entry.
 * @param {object} entry - `SubagentListEntry`-shaped row.
 * @returns {CardStatus} the status a card renders.
 */
function statusOf(entry) {
  return entry.kind === 'diagnostic' ? 'diagnostic'
    : entry.activity === 'running' ? 'running'
      : 'idle';
}

/**
 * Turn one catalog entry into the card view model the UI renders.
 * @param {object} entry - `SubagentListEntry`-shaped row.
 * @returns {{id: string, label: string, status: CardStatus, mode: string, hasChildren: boolean, diagnostic: string}} the card.
 */
function cardOf(entry) {
  const status = statusOf(entry);
  return {
    id: entry.id,
    label: typeof entry.label === 'string' && entry.label.trim().length > 0 ? entry.label : '',
    status,
    mode: typeof entry.mode === 'string' ? entry.mode : 'unknown',
    hasChildren: entry.hasChildren === true,
    diagnostic: status === 'diagnostic' ? String(entry.reason ?? 'unavailable') : '',
  };
}

/**
 * Cards for one parent's catalog, preserving host order (createdAt, then id).
 * @param {object|undefined} catalog - `SubagentCatalogSnapshot`-shaped value.
 * @returns {Array<object>} the cards, empty when the catalog is absent.
 */
function cardsOf(catalog) {
  if (catalog === undefined || catalog === null) return [];
  const entries = catalog.entries;
  if (!Array.isArray(entries)) return [];
  return entries.map(cardOf);
}

/**
 * Build the durable address `sessions.openSubagent` needs from a card.
 *
 * The runtime validates this against the live catalog itself (the child must be
 * a healthy entry whose `mode` matches), so the mode carried here is the one
 * read off the catalog — never guessed.
 * @param {string} parentSessionId - the delegating session.
 * @param {object} card - the card view model.
 * @returns {{parentSessionId: string, childSessionId: string, mode: string}} the address.
 */
function addressOf(parentSessionId, card) {
  return {
    parentSessionId,
    childSessionId: card.id,
    mode: card.mode === 'continuable' ? 'continuable' : 'one-shot',
  };
}

/**
 * Short id for a card subtitle.
 * @param {string} id - full session id.
 * @returns {string} its first 8 characters.
 */
function shortId(id) {
  return id.length > 8 ? id.slice(0, 8) : id;
}

/**
 * Extract the child session id the inline card should target from the settled
 * tool result's rendered text (`started subagent <id>`), falling back to empty
 * while the call is still in flight.
 * @param {object|null} result - the settled `ToolResultNode`, if any.
 * @returns {string} the child session id, or '' when not yet known.
 */
function childIdOfResult(result) {
  if (result === null || result === undefined) return '';
  const content = result.content;
  if (!Array.isArray(content)) return '';
  for (const block of content) {
    if (block === null || typeof block !== 'object') continue;
    if (typeof block.text !== 'string') continue;
    const match = block.text.match(/started subagent (\S+)/);
    if (match !== null) return match[1];
  }
  return '';
}

/**
 * Read the delegated task description out of the frozen tool-call arguments.
 * @param {string} argsRaw - the tool call's raw JSON arguments.
 * @returns {string} the description, or '' when absent or unparsable.
 */
function descriptionOfArgs(argsRaw) {
  if (typeof argsRaw !== 'string' || argsRaw.length === 0) return '';
  try {
    const parsed = JSON.parse(argsRaw);
    if (parsed === null || typeof parsed !== 'object') return '';
    return typeof parsed.description === 'string' ? parsed.description : '';
  } catch {
    return '';
  }
}

/**
 * Human duration from a millisecond span.
 * @param {number} ms - the span.
 * @returns {string} a compact duration, or '' when the span is unknown.
 */
function durationOf(ms) {
  if (!Number.isFinite(ms) || ms < 0) return '';
  const total = Math.floor(ms / 1000);
  const minutes = Math.floor(total / 60);
  const seconds = total % 60;
  if (minutes > 0) return `${minutes}m ${seconds}s`;
  if (total > 0) return `${total}s`;
  return `${Math.floor(ms)}ms`;
}
//#endregion

//#region src/client/style.js
/**
 * Panel styles, injected as one `<style>` element for the fiber's lifetime.
 *
 * Colors ride the shell's theme custom properties where they exist and fall
 * back to neutral values, so the panel stays legible under any theme instead of
 * hard-coding a palette.
 */

/** @type {string} the stylesheet text. */
const STYLE = `
.sap-badge{display:inline-flex;align-items:center;gap:4px;font-size:11px;line-height:1;
  padding:3px 6px;border-radius:999px;border:1px solid var(--dsh-border,rgba(128,128,128,.35));
  color:var(--dsh-fg-muted,#8b8b8b);white-space:nowrap}
.sap-dot{width:6px;height:6px;border-radius:50%;background:currentColor;flex:none}
.sap-badge-running .sap-dot{background:#22a06b;animation:sap-pulse 1.2s ease-in-out infinite}
.sap-badge-diagnostic{color:#c0533f}
@keyframes sap-pulse{0%,100%{opacity:1}50%{opacity:.35}}

.sap-card{display:flex;flex-direction:column;gap:6px;width:100%;text-align:left;
  padding:10px 12px;border-radius:10px;cursor:pointer;
  border:1px solid var(--dsh-border,rgba(128,128,128,.28));
  background:var(--dsh-bg-subtle,rgba(128,128,128,.06));
  color:inherit;font:inherit;transition:background .15s ease,border-color .15s ease}
.sap-card:hover:not(:disabled){background:var(--dsh-bg-hover,rgba(128,128,128,.13));
  border-color:var(--dsh-border-strong,rgba(128,128,128,.5))}
.sap-card:disabled{cursor:default;opacity:.75}
.sap-card:focus-visible{outline:2px solid var(--dsh-accent,#4c8bf5);outline-offset:2px}
.sap-card-head{display:flex;align-items:center;justify-content:space-between;gap:8px}
.sap-card-title{font-size:13px;font-weight:600;overflow:hidden;text-overflow:ellipsis;
  white-space:nowrap}
.sap-card-meta{display:flex;align-items:center;gap:10px;font-size:11px;
  color:var(--dsh-fg-muted,#8b8b8b)}
.sap-card-id{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}

.sap-trigger{position:fixed;right:18px;bottom:18px;z-index:55;display:inline-flex;
  align-items:center;gap:8px;padding:8px 12px;border-radius:999px;cursor:pointer;
  font:inherit;font-size:12px;
  border:1px solid var(--dsh-border,rgba(128,128,128,.3));
  background:var(--dsh-bg,#fff);color:inherit;
  box-shadow:0 4px 14px rgba(0,0,0,.14)}
.sap-trigger:hover{background:var(--dsh-bg-hover,rgba(128,128,128,.1))}
.sap-trigger-open{border-color:var(--dsh-accent,#4c8bf5)}
.sap-count{font-variant-numeric:tabular-nums;color:var(--dsh-fg-muted,#8b8b8b)}
.sap-dot-inline{background:#22a06b}
.sap-list{position:fixed;right:18px;bottom:62px;z-index:56;display:flex;
  flex-direction:column;gap:8px;width:320px;max-height:52vh;overflow-y:auto;
  padding:10px;border-radius:12px;
  border:1px solid var(--dsh-border,rgba(128,128,128,.28));
  background:var(--dsh-bg,#fff);color:inherit;
  box-shadow:0 10px 30px rgba(0,0,0,.18)}
.sap-hint{margin:0;font-size:12px;color:var(--dsh-fg-muted,#8b8b8b);padding:4px 2px}
`;
//#endregion

//#region src/client/components.js
/**
 * React components for the subagent panel.
 *
 * Plain JavaScript (no JSX — no build step in this environment), so every
 * element is a `React.createElement` call. These render ONLY the entry points;
 * the subagent's own session is rendered by the shell's conversation view after
 * `sessions.openSubagent(address)` navigates to it. Deliberately no transcript
 * renderer of our own — duplicating the shell's session view is what made the
 * first version show "too much else".
 */
var React = require("react");

/** @typedef {import('./locales.js').Translate} Translate */

/**
 * A small status pill; the dot pulses only while the child is running.
 * @param {{status: string, t: Translate}} props - status and translator.
 * @returns {object} the element.
 */
function StatusBadge(props) {
  const {status, t} = props;
  const label = status === 'running' ? t('card.running')
    : status === 'diagnostic' ? t('card.diagnostic')
      : t('card.inactive');
  return React.createElement('span', {className: `sap-badge sap-badge-${status}`},
    React.createElement('span', {className: 'sap-dot'}),
    label,
  );
}

/**
 * The inline subagent card: the entry point that replaces the generic
 * `subagent` / `subagent_fork` tool row.
 *
 * Shows the delegated task, the live status, the short child id, elapsed time,
 * and whether the child spawned nested subagents. Activating it navigates the
 * stage to the child session through the same path the session header's
 * subagent catalog uses, so the child opens as an ordinary session.
 * @param {object} props - card props.
 * @param {object} props.card - the card view model from `cardsOf`.
 * @param {string} props.fallbackLabel - description read from the call arguments.
 * @param {boolean} props.running - whether the child is still running.
 * @param {number} props.elapsedMs - span since the call started; -1 when unknown.
 * @param {boolean} props.disabled - whether this row can open the session yet.
 * @param {Translate} props.t - translator.
 * @param {() => void} props.onOpen - navigate to the child session.
 * @returns {object} the element.
 */
function SubagentCard(props) {
  const {card, fallbackLabel, running, elapsedMs, disabled, t, onOpen} = props;
  const label = card.label.length > 0 ? card.label : fallbackLabel;
  const elapsed = durationOf(elapsedMs);
  return React.createElement('button', {
    type: 'button',
    className: 'sap-card',
    onClick: onOpen,
    disabled: disabled === true,
    title: t('card.open'),
  },
  React.createElement('div', {className: 'sap-card-head'},
    React.createElement('span', {className: 'sap-card-title'},
      label.length > 0 ? label : t('card.noLabel'),
    ),
    React.createElement(StatusBadge, {status: running ? 'running' : card.status, t}),
  ),
  React.createElement('div', {className: 'sap-card-meta'},
    card.id.length > 0
      ? React.createElement('span', {className: 'sap-card-id'}, shortId(card.id))
      : null,
    elapsed.length > 0 ? React.createElement('span', {className: 'sap-card-time'}, elapsed) : null,
    card.hasChildren ? React.createElement('span', {className: 'sap-card-nested'}, t('card.children')) : null,
  ),
  );
}

/**
 * The sidebar trigger: a compact count of this session's subagents that toggles
 * the floating list.
 * @param {object} props - trigger props.
 * @param {number} props.count - how many subagents this session has.
 * @param {boolean} props.hasRunning - whether any of them is still running.
 * @param {boolean} props.open - whether the list is showing.
 * @param {Translate} props.t - translator.
 * @param {() => void} props.onToggle - toggle the floating list.
 * @returns {object} the element.
 */
function SubagentTrigger(props) {
  const {count, hasRunning, open, t, onToggle} = props;
  return React.createElement('button', {
    type: 'button',
    className: `sap-trigger${open ? ' sap-trigger-open' : ''}`,
    onClick: onToggle,
    'aria-expanded': open ? 'true' : 'false',
    title: t('trigger.label'),
  },
  React.createElement('span', null, t('trigger.label')),
  React.createElement('span', {className: 'sap-count'}, String(count)),
  hasRunning ? React.createElement('span', {className: 'sap-dot sap-dot-inline'}) : null,
  );
}

/**
 * The floating list opened by the sidebar trigger: every subagent of the
 * current session as a clickable card.
 * @param {object} props - list props.
 * @param {Array<object>} props.cards - this session's cards.
 * @param {Translate} props.t - translator.
 * @param {(card: object) => void} props.onOpen - navigate to one child session.
 * @returns {object} the element.
 */
function SubagentList(props) {
  const {cards, t, onOpen} = props;
  if (cards.length === 0) {
    return React.createElement('div', {className: 'sap-list'},
      React.createElement('p', {className: 'sap-hint'}, t('trigger.empty')),
    );
  }
  return React.createElement('div', {className: 'sap-list'},
    cards.map((card) => React.createElement(SubagentCard, {
      key: card.id,
      card,
      fallbackLabel: '',
      running: card.status === 'running',
      elapsedMs: -1,
      disabled: card.status === 'diagnostic',
      t,
      onOpen: () => onOpen(card),
    })),
  );
}
//#endregion

//#region src/client/index.js
/**
 * Browser half of dsh-subagent-panel.
 *
 * Two surfaces, both driven by the catalog `ctx.sessions` already projects:
 *  - an inline card in place of the generic `subagent` / `subagent_fork` tool
 *    row (`tool.call.toolview`, keyed by wire tool name — unclaimed, so
 *    registering owns the card);
 *  - a sidebar trigger listing every subagent of the current session.
 *
 * Activating either one calls `sessions.openSubagent(address)` — the exact
 * navigation the session header's subagent catalog uses — so the child opens as
 * an ordinary session rendered by the shell's own conversation view. This
 * plugin renders no transcript of its own: the shell already renders a session
 * better than a plugin can, and duplicating it is what made the first version
 * show "too much else".
 */
var React = require("react");




/** Package name — must equal the cordis row id and the package.json name. */
const name = 'dsh-subagent-panel';

/** Client services this half injects. */
const inject = ['slots', 'sessions', 'locale'];

/** Keyed inline card slot, dispatched by wire tool name. */
const TOOLVIEW_SLOT = 'tool.call.toolview';
/** Additive frame-wide floating layer: the trigger lives here. */
const OVERLAY_SLOT = 'shell.overlay';

/** Wire tool names whose generic row this plugin replaces with a card. */
const TOOL_KEYS = ['subagent', 'subagent_fork'];

/**
 * Plugin body: register the locale, styles, the inline card, and the trigger.
 * @param {object} ctx - client cordis context.
 */
function apply(ctx) {
  ctx.effect(function* () {
    yield ctx.locale.register(NS, {zh, en});
    const t = ctx.locale.bind(NS);

    const style = document.createElement('style');
    style.dataset.plugin = name;
    style.textContent = STYLE;
    document.head.appendChild(style);

    const slots = ctx.slots;
    /**
     * Navigate the stage to one child session.
     * @param {string} parentSessionId - the delegating session.
     * @param {object} card - the card to open.
     */
    const openChild = (parentSessionId, card) => {
      ctx.sessions.openSubagent(addressOf(parentSessionId, card));
    };

    yield slots.inject(TOOLVIEW_SLOT, () => {
      const disposers = TOOL_KEYS.map((key) => slots.register(
        {name: TOOLVIEW_SLOT, key, registrant: name},
        createCardView({ctx, t, openChild}),
      ));
      return disposers;
    });

    yield slots.inject(OVERLAY_SLOT, () => slots.register(
      {name: OVERLAY_SLOT, id: name, order: 1000},
      createTrigger({ctx, t, openChild}),
    ));

    yield () => {
      style.remove();
    };
  }, 'dsh-subagent-panel client lifecycle');
}

/**
 * Build the sidebar trigger component: a live count plus the floating list.
 * @param {object} options - context, translator, and the open action.
 * @returns {Function} the slot component.
 */
function createTrigger(options) {
  const {ctx, t, openChild} = options;
  return function SubagentTriggerHost() {
    const [listOpen, setListOpen] = React.useState(false);
    const sessionId = ctx.sessions.list.getSnapshot().current;
    if (sessionId === undefined) return null;
    const cards = cardsOf(ctx.sessions.list.getSnapshot().subagentsByParent[sessionId]);
    const hasRunning = cards.some((card) => card.status === 'running');
    return React.createElement(React.Fragment, null,
      React.createElement(SubagentTrigger, {
        count: cards.length,
        hasRunning,
        open: listOpen,
        t,
        onToggle: () => setListOpen((previous) => !previous),
      }),
      listOpen
        ? React.createElement(SubagentList, {
          cards,
          t,
          onOpen: (card) => {
            setListOpen(false);
            openChild(sessionId, card);
          },
        })
        : null,
    );
  };
}

/**
 * Elapsed span for a still-running call, whose only timestamp is the call's own
 * epoch-ms `time`. Returns -1 rather than a nonsense value when that timestamp
 * is missing or not a plausible past epoch (some fixtures carry a
 * `performance.now()`-style value), so the card simply omits the duration
 * instead of showing a five-digit minute count.
 * @param {unknown} time - the call's logged time.
 * @returns {number} elapsed ms, or -1 when unknown.
 */
function elapsedFromCall(time) {
  if (typeof time !== 'number' || !Number.isFinite(time) || time <= 0) return -1;
  const elapsed = Date.now() - time;
  return elapsed >= 0 && elapsed < 86400000 ? elapsed : -1;
}

/**
 * Build the keyed card component for one wire tool name.
 *
 * The card's identity is resolved in two steps: once the call settles its
 * rendered text carries the child id (`started subagent <id>`); while it is
 * still in flight the card shows the task description from the call arguments
 * and stays inert, because there is no catalog entry to navigate to yet.
 * @param {object} options - context, translator, and the open action.
 * @returns {Function} the slot component.
 */
function createCardView(options) {
  const {ctx, t, openChild} = options;
  return function SubagentCardView(props) {
    const {block, sessionId} = props;
    const running = block.kind !== 'tool-result';
    // The two block shapes carry the arguments in different places: a settled
    // `ToolResultNode` nests them under `call`, a `RunningToolCall` exposes them
    // at the top level.
    const call = block.call ?? null;
    const argsRaw = call !== null
      ? (call.argsRaw ?? '')
      : (typeof block.argsRaw === 'string' ? block.argsRaw : '');
    const fallbackLabel = descriptionOfArgs(argsRaw);
    const explicitId = running ? '' : childIdOfResult(block);
    const cards = cardsOf(ctx.sessions.list.getSnapshot().subagentsByParent[sessionId]);
    const card = explicitId.length > 0
      ? (cards.find((entry) => entry.id === explicitId) ?? null)
      : null;

    // Still in flight (or the child has not registered yet): show the task and
    // stay inert rather than guessing which catalog entry this call started.
    if (card === null) {
      return React.createElement(SubagentCard, {
        card: {id: '', label: '', status: 'idle', mode: 'unknown', hasChildren: false, diagnostic: ''},
        fallbackLabel,
        running,
        elapsedMs: elapsedFromCall(block.time),
        disabled: true,
        t,
        onOpen: () => {},
      });
    }

    const elapsedMs = block.callTime === null || block.callTime === undefined || block.callTime < 0
      ? -1
      : (block.time - block.callTime);
    return React.createElement(SubagentCard, {
      card,
      fallbackLabel,
      running: running || card.status === 'running',
      elapsedMs,
      disabled: card.status === 'diagnostic',
      t,
      onOpen: () => openChild(sessionId, card),
    });
  };
}
//#endregion
module.exports = { name: name, inject: inject, apply: apply };

    return module.exports;
  }
});
