#!/usr/bin/env node
/**
 * Build both halves of the package into lib/:
 *  - src/client/* -> lib/client.js (browser bundle)
 *  - src/host/*   -> lib/*.js      (plain ESM copy)
 *
 * `lib/` is a build artifact in its entirety, so `rm -rf lib && npm run build`
 * always reproduces a working package. The host sources used to live directly in
 * `lib/` next to the generated bundle, which meant one clean rebuild silently
 * deleted them; keeping every source under `src/` is what prevents that.
 *
 * The client bundling is a lexical inlining pass rather than a compile: strip
 * import/export syntax from each module, wrap every module in the CommonJS shim
 * the client module loader hands its factory, and concatenate them in dependency
 * order inside `window.__ModuleLoader__.load({ id, factory })`.
 *
 * The result is a single self-contained classic script — the exact shape
 * `dsh-client-modules` loads — with `react`, `react-dom`, and `react/jsx-runtime`
 * left external (they stay loader statics).
 *
 * This pass is intentionally conservative: it understands only the import/export
 * forms used by these files. Richer syntax needs a real bundler.
 */
import {copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const srcDir = join(root, 'src', 'client');
const hostSrcDir = join(root, 'src', 'host');
const libDir = join(root, 'lib');
const outFile = join(libDir, 'client.js');
const bundleId = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).name;

/** Modules in dependency order: leaves first, the entry (index) last. */
const order = ['locales.js', 'pure.js', 'style.js', 'components.js', 'index.js'];


/**
 * Rewrite one module's source into CommonJS-in-shim form.
 *
 * @param {string} source - module source text.
 * @returns {{code: string, exports: string[]}} the rewritten body and its export names.
 */
function toCommonJs(source) {
  const exports = [];
  let code = source;

  // `export const/function/class NAME` -> plain declaration + export binding.
  code = code.replace(
    /^export\s+(const|function|class)\s+([A-Za-z_$][\w$]*)/gm,
    (_match, kind, id) => {
      exports.push(id);
      return `${kind} ${id}`;
    },
  );

  // `export { a, b };` -> record the bindings (already declared above).
  code = code.replace(/^export\s+\{([^}]*)\};?\s*$/gm, (_match, names) => {
    for (const name of names.split(',')) {
      const trimmed = name.trim();
      if (trimmed.length > 0) exports.push(trimmed);
    }
    return '';
  });

  // `import X, { a, b } from 'spec';`, `import { a } from 'spec';`, `import X from 'spec';`
  code = code.replace(
    /^import\s+([^;]*?)\s+from\s+['"]([^'"]+)['"];?\s*$/gm,
    (_match, clause, spec) => {
      // Relative modules are inlined into this one scope: their bindings are
      // already declared here, so the import statement simply disappears.
      if (spec.startsWith('./')) return '';
      // Pull the braced group out first — it may contain commas, so splitting the
      // clause on commas would tear it apart.
      let rest = clause;
      let namedBindings = [];
      const named = /\{([^}]*)\}/.exec(rest);
      if (named !== null) {
        namedBindings = named[1].split(',').map((binding) => binding.trim())
          .filter((binding) => binding.length > 0);
        rest = rest.replace(named[0], '');
      }
      const defaultName = rest.split(',').map((part) => part.trim())
        .find((part) => part.length > 0);
      const lines = [];
      if (defaultName !== undefined) {
        lines.push(`var ${defaultName} = require(${JSON.stringify(spec)});`);
      }
      if (namedBindings.length > 0) {
        lines.push(`var {${namedBindings.join(', ')}} = require(${JSON.stringify(spec)});`);
      }
      return lines.join('\n');
    },
  );

  return {code, exports};
}

const chunks = [];
for (const file of order) {
  const source = readFileSync(join(srcDir, file), 'utf8');
  const {code, exports} = toCommonJs(source);
  chunks.push(`\n//#region src/client/${file}\n${code.trim()}\n//#endregion`);
  if (file === 'index.js') {
    chunks.push(`module.exports = { ${exports.map((id) => `${id}: ${id}`).join(', ')} };`);
  }
}

const bundle = `/* ${bundleId} client bundle — generated by scripts/build.mjs from src/client/ */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(bundleId)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
${chunks.join('\n')}

    return module.exports;
  }
});
`;

mkdirSync(dirname(outFile), {recursive: true});
writeFileSync(outFile, bundle);
process.stdout.write(`built ${outFile} (${bundle.length} bytes)\n`);

// The host half is plain ESM that Node loads as-is, so it is copied verbatim.
for (const file of readdirSync(hostSrcDir)) {
  if (!file.endsWith('.js')) continue;
  const target = join(libDir, file);
  copyFileSync(join(hostSrcDir, file), target);
  process.stdout.write(`copied ${target}\n`);
}
